from typing import List, Optional

from pydantic import BaseModel, Field


class TeamMember(BaseModel):
    name: str = Field(
        description="Full name of the leadership or team member."
    )

    role: str = Field(
        description="Job title or role of the person."
    )

    linkedin_url: Optional[str] = Field(
        default=None,
        description="Public LinkedIn profile URL if discovered."
    )

    linkedin_source: Optional[str] = Field(
        default=None,
        description=(
            "How the LinkedIn URL was discovered. "
            "Use 'website' when found on the company website, "
            "'search' when discovered through external search, "
            "or null when no URL was found."
        ),
    )


class UsageStats(BaseModel):
    input_tokens: int = Field(
        default=0,
        ge=0,
        description="Number of input tokens used by the LLM."
    )

    output_tokens: int = Field(
        default=0,
        ge=0,
        description="Number of output tokens generated by the LLM."
    )

    total_tokens: int = Field(
        default=0,
        ge=0,
        description="Total input and output tokens."
    )

    estimated_cost_usd: float = Field(
        default=0.0,
        ge=0,
        description="Estimated LLM API cost in USD."
    )


class CompanyIntelligence(BaseModel):
    domain: str = Field(
        description="The company domain being analyzed."
    )

    company_name: str = Field(
        description="The company or organization name."
    )

    company_overview: str = Field(
        description=(
            "A concise two-sentence explanation "
            "of what the company does."
        )
    )

    target_audience: str = Field(
        description=(
            "The ideal customer profile or "
            "primary target audience."
        )
    )

    contact_emails: List[str] = Field(
        default_factory=list,
        description=(
            "Generic or public email addresses "
            "found on the website."
        )
    )

    leadership_team: List[TeamMember] = Field(
        default_factory=list,
        description=(
            "Important founders, executives, "
            "or team members discovered from the website."
        )
    )

    source_pages: List[str] = Field(
        default_factory=list,
        description=(
            "URLs that contained useful evidence "
            "for the extracted information."
        )
    )

    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description=(
            "Estimated confidence in the completeness "
            "and correctness of the extracted information."
        )
    )

    usage: UsageStats = Field(
        default_factory=UsageStats,
        description="LLM token and cost statistics."
    )